### ISSUE TITLE
Module 3: Microsoft case study, the year is unclear. 

### ISSUE THREAD

**Issue by winterrocks** [todogroup/ospo-career-path#31]
https://github.com/todogroup/ospo101/blob/main/module3/README.md#open-source-in-earnest

It says:
> About three years ago, things began to change. Microsoft decided to make open source pervasive throughout the company and rolled open source into the main engineering groups.

Now it is impossible to know what this "About three years ago" means, because it is not clear when that was said. It would be better to put something like: "Around the year 201x things began to change" and change 201x to the correct year.

**Comment by shebuel-oss** [comment]
**Working on this issue.**
