### ISSUE TITLE
Images not visible 

### ISSUE THREAD

**Issue by chandhanarao** [todogroup/ospo-career-path#54]
The images under the headers are not visible. I am able to see them only when I download.

**Comment by anajsana** [comment]
Hello @chandhanarao. Thanks for raising this issue. Coudl you please specify which images are you describing? I'm double-checking the README.md from each module and they render fine on my end 🙂 

![Screenshot 2022-12-15 at 20-18-46 todogroup_ospo-career-path OSPO 101 Training Modules](https://user-images.githubusercontent.com/43671777/207846424-777bfa0c-9a1c-4c0c-a2c1-255ea9450165.png)
