### ISSUE TITLE
Review and complete the set of courses on README.md

### ISSUE THREAD

**Issue by anajsana** [todogroup/ospo-career-path#59]
Collect all courses out there relevant to OSPO-related work and create a path. Review `Career Path progression` section and identify:

* Existing courses (outside TODO) that can be added
* Give an order to the list (from beginner to advance)
* Identify new courses that does not exist and the community would like to create

**Comment by anajsana** [comment]
Maybe as [cornelius](https://github.com/cornelius) suggested, courses can be divided into different personas:

1. Management
2. Employee Contributors
3. Stakeholders (?)

## OSPO Management courses

* OSPO 101
* Implementing Open Source License Compliance Management (LFC194)
* Introduction to DevSecOps for Managers (LFS180x)
* Introduction to Open Source License Compliance Management (LFC193)
* [Antitrust Laws and Open Source Software Project Management and Participation (LFC105)](https://training.linuxfoundation.org/training/antitrust-laws-and-open-source-software-project-management-and-participation-lfc105/)

## Employee Contributors

* [Developing Secure Software(LFD121)](https://training.linuxfoundation.org/training/developing-secure-software-lfd121/)
* A Beginner’s Guide to Open Source Software Development (LFD102)
* Open Source Licensing Basics for Software Developers (LFC191)

> Feel free to add other free courses available in other spaces!

**Comment by anajsana** [comment]
Here is a list of available open source training courses to start with:

## OSPO Management

Policy and Compliance:

* Open Source Program Office Essentials - The Linux Foundation - This course covers the essentials of building and managing an open source program office. It provides an overview of open source licensing, governance, community management, and more. It is suitable for managers who are new to open source program management. https://training.linuxfoundation.org/training/open-source-program-office-essentials/

* OpenChain Conformance Training - OpenChain - This course covers the OpenChain standard for open source compliance. It is designed for managers who need to ensure their organization is complying with open source licensing requirements. https://www.openchainproject.org/conformance/training

Community Engagement:

* Open Source Community Management - The Linux Foundation - This course covers community management best practices for open source projects. It is designed for managers who want to engage with and build a community around their open source projects. https://training.linuxfoundation.org/training/open-source-community-management/

* Building Effective Open Source Programs - The Linux Foundation - This course covers the strategies and tactics for building effective open source programs. It is designed for managers who want to build and lead successful open source programs. https://training.linuxfoundation.org/training/building-effective-open-source-programs/

Legal Support:

* Open Source Licensing Basics for Lawyers - The Linux Foundation - This course covers the basics of open source licensing and compliance from a legal perspective. It is designed for lawyers who need to understand the legal aspects of open source licensing and compliance. https://training.linuxfoundation.org/training/open-source-licensing-basics-for-lawyers/

* Open Source License Compliance for Lawyers - The Linux Foundation - This course covers the legal and technical aspects of open source license compliance. It is designed for lawyers who need to ensure their organization is complying with open source licensing requirements. https://training.linuxfoundation.org/training/open-source-license-compliance-for-lawyers/

Technical Integration:

* Open Source Management & Strategy - The Linux Foundation - This course covers the strategic and technical aspects of open source program management, including open source program management tools and technical integration. It is suitable for managers who want to develop a deep understanding of open source program management. https://training.linuxfoundation.org/training/open-source-management-strategy/

* Open Source Development with Git - The Linux Foundation - This course covers using Git for open source development. It covers topics such as branching and merging, rebasing, and resolving conflicts. It is suitable for managers who need to understand Git and its use in open source projects. https://training.linuxfoundation.org/training/open-source-development-with-git/

Contribution and Management:

* Open Source Management & Strategy - The Linux Foundation - This course covers the strategic and tactical aspects of open source program management, including open source contribution and management. It is suitable for managers who want to develop a deep understanding of open source program management. https://training.linuxfoundation.org/training/open-source-management-strategy/

* Open Source Community Management - The Linux Foundation - This course covers community management best practices for open source projects. It is designed for managers who want to engage with and build a community around their open source projects. https://training.linuxfoundation.org/training/open-source-community-management/

Ecosystem Management:

* Building Effective Open Source Programs - The Linux Foundation - This course covers the strategies and tactics for building effective open source programs. It is designed for managers who want to build and lead successful open source programs

**Comment by anajsana** [comment]
## Open Source Contributors (from Organizations)

Policy and Compliance:

* Open Source Licensing Basics - The Linux Foundation - This course covers the basics of open source licensing and compliance. It is designed for open source contributors who need to understand open source licensing and compliance requirements. https://training.linuxfoundation.org/training/open-source-licensing-basics/

* OpenChain Conformance Training - OpenChain - This course covers the OpenChain standard for open source compliance. It is designed for open source contributors who need to ensure their organization is complying with open source licensing requirements. https://www.openchainproject.org/conformance/training

Community Engagement:

* Open Source Community Management - The Linux Foundation - This course covers community management best practices for open source projects. It is designed for open source contributors who want to engage with and build a community around their open source projects. https://training.linuxfoundation.org/training/open-source-community-management/

* Building and Managing an Open Source Community - The Linux Foundation - This course covers the strategies and tactics for building and managing an open source community. It is designed for open source contributors who want to contribute to and build successful open source communities. https://training.linuxfoundation.org/training/building-and-managing-an-open-source-community/

Legal Support:

* Open Source License Compliance for Developers - The Linux Foundation - This course covers the legal and technical aspects of open source license compliance. It is designed for open source contributors who need to ensure their contributions comply with open source licensing requirements. https://training.linuxfoundation.org/training/open-source-license-compliance-for-developers/

* Open Source Licensing and Patents - The Linux Foundation - This course covers open source licensing and patent issues, including licensing and patent policies, contributor agreements, and patent license agreements. It is designed for open source contributors who need to understand the legal aspects of open source licensing and patent issues. https://training.linuxfoundation.org/training/open-source-licensing-and-patents/

Technical Integration:

* Open Source Development with Git - The Linux Foundation - This course covers using Git for open source development. It covers topics such as branching and merging, rebasing, and resolving conflicts. It is suitable for open source contributors who need to understand Git and its use in open source projects. https://training.linuxfoundation.org/training/open-source-development-with-git/

* Continuous Integration and Continuous Deployment with Jenkins - The Linux Foundation - This course covers using Jenkins for continuous integration and continuous deployment. It is designed for open source contributors who need to understand how to set up and use Jenkins for their open source projects. https://training.linuxfoundation.org/training/continuous-integration-continuous-deployment-with-jenkins/

Contribution and Management:

* Open Source Contribution Fundamentals - The Linux Foundation - This course covers the fundamentals of contributing to open source projects. It is designed for open source contributors who are new to open source contribution and want to learn the basics. https://training.linuxfoundation.org/training/open-source-contribution-fundamentals/

* Effective Open Source Contribution - The Linux Foundation - This course covers the strategies and tactics for effective open source contribution. It is designed for open source contributors who want to contribute more effectively to open source projects. https://training.linuxfoundation.org/training/effective-open-source-contribution/

Ecosystem Management:

* Building and Managing an Open Source Community - The Linux Foundation - This course covers the strategies and tactics for building and managing an open source community

**Comment by anajsana** [comment]
## Organization Stakeholders Engaging with OSPO

Policy and Compliance:

* Open Source Compliance for Managers - The Linux Foundation - This course covers the legal and business aspects of open source compliance. It is designed for managers who need to understand open source compliance requirements and how to ensure their organization is compliant. https://training.linuxfoundation.org/training/open-source-compliance-for-managers/

* OpenChain Conformance Training - OpenChain - This course covers the OpenChain standard for open source compliance. It is designed for organization stakeholders who need to understand open source compliance requirements and how to ensure their organization is compliant. https://www.openchainproject.org/conformance/training

Community Engagement:

* Open Source Community Management - The Linux Foundation - This course covers community management best practices for open source projects. It is designed for organization stakeholders who need to engage with and understand open source communities. https://training.linuxfoundation.org/training/open-source-community-management/

* Building and Managing an Open Source Community - The Linux Foundation - This course covers the strategies and tactics for building and managing an open source community. It is designed for organization stakeholders who need to understand open source communities and how to contribute to them. https://training.linuxfoundation.org/training/building-and-managing-an-open-source-community/

Legal Support:

* Open Source Licensing Basics for Non-Lawyers - The Linux Foundation - This course covers the basics of open source licensing and compliance for non-lawyers. It is designed for organization stakeholders who need to understand open source licensing and compliance requirements. https://training.linuxfoundation.org/training/open-source-licensing-basics-for-non-lawyers/

* Open Source Licensing and Patents - The Linux Foundation - This course covers open source licensing and patent issues, including licensing and patent policies, contributor agreements, and patent license agreements. It is designed for organization stakeholders who need to understand the legal aspects of open source licensing and patent issues. https://training.linuxfoundation.org/training/open-source-licensing-and-patents/

Technical Integration:

* Introduction to DevOps and Site Reliability Engineering - The Linux Foundation - This course covers the principles of DevOps and Site Reliability Engineering (SRE). It is designed for organization stakeholders who need to understand how open source projects use DevOps and SRE principles. https://training.linuxfoundation.org/training/introduction-to-devops-and-site-reliability-engineering/

Contribution and Management:

* Open Source Contribution Fundamentals for Non-Developers - The Linux Foundation - This course covers the basics of contributing to open source projects for non-developers. It is designed for organization stakeholders who want to understand open source contribution and how to contribute to open source projects. https://training.linuxfoundation.org/training/open-source-contribution-fundamentals-for-non-developers/

* Effective Open Source Contribution - The Linux Foundation - This course covers the strategies and tactics for effective open source contribution. It is designed for organization stakeholders who want to contribute more effectively to open source projects. https://training.linuxfoundation.org/training/effective-open-source-contribution/

**Comment by cornelius** [comment]
@anajsana The links to the courses don't seem to work anymore. Has something changed on the LF training web site?

**Comment by anajsana** [comment]
Old issue. creating new issues based on the new structure, personas and action items defined in the working group
