### ISSUE TITLE
Define personas for the OSPO Career Path (Audience)

### ISSUE THREAD

**Issue by anajsana** [todogroup/ospo-career-path#60]
A simple division can be:

* (1) Open Source /OSPO managers *shaping the process* within an organization 
* (2) Open Source /OSPO contributors within and organization (code and non-code contributors) 
* (3) Open Source /OSPO managers *executing the process*

**Comment by cornelius** [comment]
I would focus on (1) and (2) as the main personas from the point of view of TODO group trainings. (3) will very much depend on the constraints, culture, practices within the specific organization where the process is executed, so a generic training will only be of limited use.

There could be another persona:

(4) Software staff within an organization which is involved in consuming open source software

This will have generic needs, but there also will be a very organization specific part. There probably also is a transition path between (4) and (2) as organizations should encourage consumers of open source software to also become contributors.
